# Importing labrary

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the file

In [51]:
df =pd.read_excel(r"Telco_customer_churn.xlsx/Telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

# Exploring

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

# checking missing values

In [53]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

# descripitive statsistics/ descripitive Analysis

In [54]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

# Exploring

In [55]:
df['Churn Reason'].isnull().sum()

np.int64(5174)

# count of customer city wise

In [56]:
df['City'].value_counts()

City
Los Angeles       305
San Diego         150
San Jose          112
Sacramento        108
San Francisco     104
                 ...
Milford             4
Calpine             4
Standish            4
Tulelake            4
Olympic Valley      4
Name: count, Length: 1129, dtype: int64

# Payment Methods
# Internet services
# streaming movies

In [57]:
df['Payment Method'].value_counts()
df['Internet Service'].value_counts()
df['Streaming Movies'].value_counts()

Streaming Movies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

# filter out row where churn value is 1

In [58]:
Churned_Customer=df[df["Churn Value"]==1]
Churned_Customer.info()

<class 'pandas.DataFrame'>
RangeIndex: 1869 entries, 0 to 1868
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         1869 non-null   str
 1   Count              1869 non-null   int64
 2   Country            1869 non-null   str
 3   State              1869 non-null   str
 4   City               1869 non-null   str
 5   Zip Code           1869 non-null   int64
 6   Lat Long           1869 non-null   str
 7   Latitude           1869 non-null   float64
 8   Longitude          1869 non-null   float64
 9   Gender             1869 non-null   str
 10  Senior Citizen     1869 non-null   str
 11  Partner            1869 non-null   str
 12  Dependents         1869 non-null   str
 13  Tenure Months      1869 non-null   int64
 14  Phone Service      1869 non-null   str
 15  Multiple Lines     1869 non-null   str
 16  Internet Service   1869 non-null   str
 17  Online Security    1869 non-null   str
 18  Online Backup      1869 non-null   str
 19  Device Protection  1869 non-null   str
 20  Tech Support       1869 non-null   str
 21  Streaming TV       1869 non-null   str
 22  Streaming Movies   1869 non-null   str
 23  Contract           1869 non-null   str
 24  Paperless Billing  1869 non-null   str
 25  Payment Method     1869 non-null   str
 26  Monthly Charges    1869 non-null   float64
 27  Total Charges      1869 non-null   object
 28  Churn Label        1869 non-null   str
 29  Churn Value        1869 non-null   int64
 30  Churn Score        1869 non-null   int64
 31  CLTV               1869 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 482.0+ KB

# DATA Engineering
Based on tenure value categorized customer as new customer , regularcustomer,loyal customer

In [59]:
df['Tenure Months'].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: Tenure Months, dtype: float64

In [60]:
bins=[-1,12,36,float('inf')]
labels=["New Customer","Regular Customer","Loyal Customer"]
df["Customer Segment"]=pd.cut(df['Tenure Months'],bins,labels=labels)

In [61]:
df['Customer Segment'].value_counts()

Customer Segment
Loyal Customer      3001
New Customer        2186
Regular Customer    1856
Name: count, dtype: int64

In [62]:
df['Monthly Charges'].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: Monthly Charges, dtype: float64

# Revenue Segmentation

In [63]:
bins=[18,40,65,90,float('inf')]
labels = ["Low","Medium","High","premium",]
df["Revenue Segment"] = pd.cut(df['Monthly Charges'], bins=bins, labels=labels)

In [64]:
df['Revenue Segment']

0        Medium
1          High
2       premium
3       premium
4       premium
         ...
7038        Low
7039       High
7040    premium
7041        Low
7042    premium
Name: Revenue Segment, Length: 7043, dtype: category
Categories (4, str): ['Low' < 'Medium' < 'High' < 'premium']

# Churn Score

In [ ]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason', 'Customer Segment',
       'Revenue Segment'],
      dtype='str')

In [66]:
df['Churn Score'].describe()

count    7043.000000
mean       58.699418
std        21.525131
min         5.000000
25%        40.000000
50%        61.000000
75%        75.000000
max       100.000000
Name: Churn Score, dtype: float64

In [70]:
bins=[4,30,60,80,100]
labels=["Low Risk","Medium Risk","High risk","Criitical Risk"]
df['Risk category']=pd.cut(df['Churn Score'],bins=bins,labels=labels)

In [72]:
df['Risk category'].value_counts()

Risk category
Medium Risk       2523
High risk         2517
Criitical Risk    1050
Low Risk           953
Name: count, dtype: int64

# Export to CSV

In [73]:
df.to_csv("Cleaned_Transformed _customer.CSV")